version: '2'
services:
  spark-slave1:
    image: lvraikkonen/spark:2.4.6
    container_name: spark-slave1
    privileged: true
    # volumes:
    #   - "./volume/hadoop/work/slave1:/works"
    #   - "./volume/hadoop/logs/slave1:/root/hadoop/logs/"
    #   - "./volume/hadoop/tmp/slave1:/tmp"
    hostname: hadoop-slave1
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 8081
    ports:
      - 8081:8081
    networks:
      spark:
        aliases: 
          - hadoop-slave1
    tty: true
    command: /usr/sbin/init
  
  spark-slave2:
    image: lvraikkonen/spark:2.4.6
    container_name: spark-slave2
    privileged: true
    # volumes:
    #   - "./volume/hadoop/work/slave2:/works"
    #   - "./volume/hadoop/logs/slave2:/root/hadoop/logs/"
    #   - "./volume/hadoop/tmp/slave2:/tmp"
    hostname: hadoop-slave2
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 8082
    ports:
      - 8082:8082
    networks:
      spark:
        aliases: 
          - hadoop-slave2
    tty: true
    command: /usr/sbin/init
      
  spark-slave3:
    image: lvraikkonen/spark:2.4.6
    container_name: spark-slave3
    privileged: true
    # volumes:
    #   - "./volume/hadoop/work/slave3:/works"
    #   - "./volume/hadoop/logs/slave3:/root/hadoop/logs/"
    #   - "./volume/hadoop/tmp/slave3:/tmp"
    hostname: hadoop-slave3
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 8083
    ports:
      - 8083:8083
    networks:
      spark:
        aliases: 
          - hadoop-slave3
    tty: true
    command: /usr/sbin/init

  mysql:
    image: mysql:5.7.30
    volumes:
      - "./volume/mysql:/var/lib/mysql"
    container_name: mysql
    hostname: mysql
    networks:
      - spark
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    tty: true

  spark-master:
    image: lvraikkonen/spark:2.4.6
    container_name: spark-master
    privileged: true
    expose:
      - 4040
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - "4040:4040"
      - "5070:50070"
      - "8088:8088"
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
      - "8090:18080" # historyserver
    # volumes:
    #   - "./volume/hadoop/work/master:/works"
    #   - "./volume/hadoop/logs/master:/root/hadoop/logs/"
    #   - "./volume/hadoop/tmp/master:/tmp"
    #   - "./volume/code:/code"
    hostname: hadoop-master
    links:
      - spark-slave1
      - spark-slave2
      - spark-slave3
      - mysql
    networks:
      spark:
        aliases: 
          - hadoop-master
    tty: true
    command: /usr/sbin/init

networks:
  spark: