version: "2.3"

services:

  zknode1:
    image: zookeeper
    container_name: zknode1
    hostname: zknode1
    volumes:
      - zknode1_data:/data
      - zknode1_log:/datalog
    networks:
      - zkNet
    environment:
       ZOO_MY_ID: 1
       ZOO_SERVERS: server.1=zknode1:2888:3888 server.2=zknode2:2888:3888 server.3=zknode3:2888:3888
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuplen | grep 2181 || exit 1"]

  zknode2:
    image: zookeeper
    container_name: zknode2
    hostname: zknode2
    volumes:
      - zknode2_data:/data
      - zknode2_log:/datalog
    networks:
      - zkNet
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zknode1:2888:3888 server.2=zknode2:2888:3888 server.3=zknode3:2888:3888
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuplen | grep 2181 || exit 1"]

  zknode3:
    image: zookeeper
    container_name: zknode3
    hostname: zknode3
    volumes:
      - zknode3_data:/data
      - zknode3_log:/datalog
    networks:
      - zkNet
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zknode1:2888:3888 server.2=zknode2:2888:3888 server.3=zknode3:2888:3888
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuplen | grep 2181 || exit 1"]
  
  kafka1:
    image: bigdata-kafka:0.2
    container_name: kafka1
    hostname: kafka1
    networks:
      - zkNet
    depends_on:
      - zknode1
      - zknode2
      - zknode3
    environment:
      KAFKA_HOST: kafka1
      KAFKA_PORT: 9092
      ZOOKEEPER_CONNECT: zknode1:2181,zknode2:2181,zknode3:2181
      KAFKA_ID: 0

  kafka2:
    image: bigdata-kafka:0.2
    container_name: kafka2
    hostname: kafka2
    networks:
      - zkNet
    depends_on:
      - zknode1
      - zknode2
      - zknode3
    environment:
      KAFKA_HOST: kafka2
      KAFKA_PORT: 9092
      ZOOKEEPER_CONNECT: zknode1:2181,zknode2:2181,zknode3:2181
      KAFKA_ID: 1

  kafka3:
    image: bigdata-kafka:0.2
    container_name: kafka3
    hostname: kafka3
    networks:
      - zkNet
    depends_on:
      - zknode1
      - zknode2
      - zknode3
    environment:
      KAFKA_HOST: kafka3
      KAFKA_PORT: 9092
      ZOOKEEPER_CONNECT: zknode1:2181,zknode2:2181,zknode3:2181
      KAFKA_ID: 2